apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simulator-app
  template:
    metadata:
      labels:
        app: simulator-app
    spec:
      containers:
      - name: simulator-app
        # IMPORTANT: Replace PROJECT_ID below
        image: your-registry/streamify-repo/simulator-app:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: logs-storage
          mountPath: /data
      volumes:
      - name: logs-storage
        persistentVolumeClaim:
          claimName: activity-logs-pvc